apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service
  description: Processes payments and manages transactions
  annotations:
    argocd/app-name: payment-service
    github.com/project-slug: saranca14/shopflow-app
    tekton.dev/pipeline: payment-service-pipeline
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: shopflow
