apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-service
  description: Manages user profiles and authentication
  annotations:
    argocd/app-name: user-service
    github.com/project-slug: saranca14/shopflow-app
    tekton.dev/pipeline: user-service-pipeline
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: shopflow
